dist: trusty
language: java
jdk:
  - oraclejdk8

script: ant

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN # Set in travis-ci.com dashboard
    file: dist/*
    skip_cleanup: true
    on:
      branch: master
